#define ProtoLineinfoEnc      VMValue3
#define ProtoLocvarsEnc       VMValue1
#define ProtoUpvaluesEnc      VMValue1
#define ProtoDebuginsnEnc     VMValue2
#define ProtoTypeinfoEnc      VMValue1
#define ProtoDebugnameEnc     VMValue4
#define ProtoSourceEnc        VMValue1
#define ProtoUserdataEnc      VMValue4
#define ProtoAbslineinfoEnc   VMValue4
#define ClosureDebugNameEnc   VMValue1
#define LuaStateStackSizeEnc  VMValue4
#define ClosureContEnc        VMValue3
#define UdataMetaEnc          VMValue3
#define TStringHashEnc        VMValue3
